# Generated by Django 5.2.6 on 2025-09-07 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="product",
            name="ai_tags",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_url",
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="features",
            field=models.JSONField(
                default=dict,
                help_text="AI-generated features stored as JSON (ImageFeatures schema)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_filename",
            field=models.CharField(
                default="",
                help_text="Unique filename of the saved image",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="source_url",
            field=models.URLField(
                db_index=True,
                default="",
                help_text="Original URL of the product",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["source_url"], name="products_source__75522d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["image_filename"], name="products_image_f_c00ec3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["created_at"], name="products_created_e1ba5f_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="product",
            table="products",
        ),
    ]
