# Generated by Django 5.2.6 on 2025-09-07 14:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("product_url", models.URLField(unique=True)),
                ("image_url", models.URLField()),
                (
                    "ai_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        db_index=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
